2016-06-07 07:38:29,402 [10] ERROR WOW.SaveTool.Data.CustomerRepository - System.TimeoutException: The request channel timed out while waiting for a reply after 00:00:02.9609961. Increase the timeout value passed to the call to Request or increase the SendTimeout value on the Binding. The time allotted to this operation may have been a portion of a longer timeout. ---> System.TimeoutException: The HTTP request to 'https://apiexternalqa.wideopenwest.com/Enterprise/WOWProduct/QA/ProductQuery/ProductQuery.svc' has exceeded the allotted timeout of 00:00:03. The time allotted to this operation may have been a portion of a longer timeout. ---> System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetResponse()
   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.HttpChannelRequest.WaitForReply(TimeSpan timeout)
   --- End of inner exception stack trace ---
   at System.ServiceModel.Channels.HttpChannelUtilities.ProcessGetResponseWebException(WebException webException, HttpWebRequest request, HttpAbortReason abortReason)
   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.HttpChannelRequest.WaitForReply(TimeSpan timeout)
   at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   --- End of inner exception stack trace ---

Server stack trace: 
   at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.SecurityChannelFactory`1.SecurityRequestChannel.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at WOW.SaveTool.Data.ProductQuery.IProductQuery.GetCustomerRating(CustomerRatingRequest customerRatingRequest)
   at WOW.SaveTool.Data.CustomerRepository.<>c__DisplayClass5.<GetCustomerRatingData>b__4() in c:\@EricStuff\WOW_Development\WOW.SavesTool\Release2\Dev\WOW.SaveTool.Data\CustomerRepository.cs:line 126
   at Polly.Policy.<>c__DisplayClass8_0`1.<Execute>b__0() in C:\projects\polly\src\Polly.Shared\Policy.cs:line 103
   at Polly.Retry.RetryEngine.Implementation(Action action, IEnumerable`1 shouldRetryPredicates, Func`1 policyStateFactory) in C:\projects\polly\src\Polly.Shared\Retry\RetryEngine.cs:line 29
   at Polly.RetrySyntax.<>c__DisplayClass3_0.<Retry>b__0(Action action, Context context) in C:\projects\polly\src\Polly.Shared\RetrySyntax.cs:line 65
   at Polly.Policy.Execute[TResult](Func`1 action, Context context) in C:\projects\polly\src\Polly.Shared\Policy.cs:line 103
   at Polly.Policy.Execute[TResult](Func`1 action) in C:\projects\polly\src\Polly.Shared\Policy.cs:line 116
   at WOW.SaveTool.Data.CustomerRepository.GetCustomerRatingData(String accountNumber) in c:\@EricStuff\WOW_Development\WOW.SavesTool\Release2\Dev\WOW.SaveTool.Data\CustomerRepository.cs:line 126
2016-06-07 07:38:34,727 [10] ERROR WOW.SaveTool.Data.CustomerRepository - System.TimeoutException: The request channel timed out while waiting for a reply after 00:00:02.9589959. Increase the timeout value passed to the call to Request or increase the SendTimeout value on the Binding. The time allotted to this operation may have been a portion of a longer timeout. ---> System.TimeoutException: The HTTP request to 'https://apiexternalqa.wideopenwest.com/Enterprise/WOWProduct/QA/ProductQuery/ProductQuery.svc' has exceeded the allotted timeout of 00:00:03. The time allotted to this operation may have been a portion of a longer timeout. ---> System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetResponse()
   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.HttpChannelRequest.WaitForReply(TimeSpan timeout)
   --- End of inner exception stack trace ---
   at System.ServiceModel.Channels.HttpChannelUtilities.ProcessGetResponseWebException(WebException webException, HttpWebRequest request, HttpAbortReason abortReason)
   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.HttpChannelRequest.WaitForReply(TimeSpan timeout)
   at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   --- End of inner exception stack trace ---

Server stack trace: 
   at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.SecurityChannelFactory`1.SecurityRequestChannel.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at WOW.SaveTool.Data.ProductQuery.IProductQuery.GetRateIncrease(GetRateIncreaseRequest rateIncreaseRequest)
   at WOW.SaveTool.Data.CustomerRepository.GetCustomerRateIncrease(String accountNumber, Package[] accountPackage, String marketId, Boolean isCable, Boolean isPhone, Boolean isInternet) in c:\@EricStuff\WOW_Development\WOW.SavesTool\Release2\Dev\WOW.SaveTool.Data\CustomerRepository.cs:line 169
2016-06-07 09:06:53,162 [6] ERROR WOW.SaveTool.Data.CustomerRepository - System.ServiceModel.FaultException`1[System.ServiceModel.ExceptionDetail]: Exception of type 'WOW.Care.Contracts.CustomExceptions.CustomException' was thrown. (Fault Detail is equal to An ExceptionDetail, likely created by IncludeExceptionDetailInFaults=true, whose value is:
WOW.Care.Contracts.CustomExceptions.CustomException: Exception of type 'WOW.Care.Contracts.CustomExceptions.CustomException' was thrown.
   at WOW.Care.Core.Customer.CustomerSearchAllBilingSystems.CustomerDetails(CustomerDetailsByAccountNumberRequest customerDetailsRequest)
   at WOW.Care.Services.Customer.<>c__DisplayClassd.<CustomerDetailsByAccountNumber>b__c()
   at WOW.Care.Core.BaseClasses.ServiceBase.ExecuteFaultHandledOperation[T](Func`1 codetoExecute, IUserDbRequest userDbRequests, IValidator validator, Object request)
   at WOW.Care.Services.Customer.CustomerDetailsByAccountNumber(CustomerDetailsByAccountNumberRequest customerDetailsRequest)
   at Castle.Proxies.Invocations.ICustomer_CustomerDetailsByAccountNumber.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at WOW.Care.Common.Logging.LoggingInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.Abs...).
2016-06-07 09:07:02,487 [10] ERROR WOW.SaveTool.Data.CustomerRepository - System.ServiceModel.FaultException`1[System.ServiceModel.ExceptionDetail]: Exception of type 'WOW.Care.Contracts.CustomExceptions.CustomException' was thrown. (Fault Detail is equal to An ExceptionDetail, likely created by IncludeExceptionDetailInFaults=true, whose value is:
WOW.Care.Contracts.CustomExceptions.CustomException: Exception of type 'WOW.Care.Contracts.CustomExceptions.CustomException' was thrown.
   at WOW.Care.Core.Customer.CustomerSearchAllBilingSystems.CustomerDetails(CustomerDetailsByAccountNumberRequest customerDetailsRequest)
   at WOW.Care.Services.Customer.<>c__DisplayClassd.<CustomerDetailsByAccountNumber>b__c()
   at WOW.Care.Core.BaseClasses.ServiceBase.ExecuteFaultHandledOperation[T](Func`1 codetoExecute, IUserDbRequest userDbRequests, IValidator validator, Object request)
   at WOW.Care.Services.Customer.CustomerDetailsByAccountNumber(CustomerDetailsByAccountNumberRequest customerDetailsRequest)
   at Castle.Proxies.Invocations.ICustomer_CustomerDetailsByAccountNumber.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at WOW.Care.Common.Logging.LoggingInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.Abs...).
2016-06-07 09:31:57,510 [9] ERROR WOW.SaveTool.Data.CustomerRepository - System.ServiceModel.FaultException`1[WOW.SaveTool.Data.ProductQuery.DbFaultException]: The INSERT statement conflicted with the FOREIGN KEY constraint "FK_SaveLogOfferSaveLog". The conflict occurred in database "GUIOverlay", table "saveTool.SaveLog", column 'saveLogId'.
The statement has been terminated. (Fault Detail is equal to WOW.SaveTool.Data.ProductQuery.DbFaultException).
2016-06-07 09:33:05,738 [11] ERROR WOW.SaveTool.Data.CustomerRepository - System.ServiceModel.FaultException`1[WOW.SaveTool.Data.ProductQuery.DbFaultException]: The INSERT statement conflicted with the FOREIGN KEY constraint "FK_SaveLogOfferSaveLog". The conflict occurred in database "GUIOverlay", table "saveTool.SaveLog", column 'saveLogId'.
The statement has been terminated. (Fault Detail is equal to WOW.SaveTool.Data.ProductQuery.DbFaultException).
2016-06-07 14:22:05,459 [7] ERROR WOW.SaveTool.Data.CustomerRepository - System.ServiceModel.FaultException`1[System.ServiceModel.ExceptionDetail]: Exception of type 'WOW.Care.Contracts.CustomExceptions.CustomException' was thrown. (Fault Detail is equal to An ExceptionDetail, likely created by IncludeExceptionDetailInFaults=true, whose value is:
WOW.Care.Contracts.CustomExceptions.CustomException: Exception of type 'WOW.Care.Contracts.CustomExceptions.CustomException' was thrown.
   at WOW.Care.Core.Customer.CustomerSearchAllBilingSystems.CustomerDetails(CustomerDetailsByAccountNumberRequest customerDetailsRequest)
   at WOW.Care.Services.Customer.<>c__DisplayClassd.<CustomerDetailsByAccountNumber>b__c()
   at WOW.Care.Core.BaseClasses.ServiceBase.ExecuteFaultHandledOperation[T](Func`1 codetoExecute, IUserDbRequest userDbRequests, IValidator validator, Object request)
   at WOW.Care.Services.Customer.CustomerDetailsByAccountNumber(CustomerDetailsByAccountNumberRequest customerDetailsRequest)
   at Castle.Proxies.Invocations.ICustomer_CustomerDetailsByAccountNumber.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at WOW.Care.Common.Logging.LoggingInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.Abs...).
2016-06-07 14:51:35,268 [7] ERROR WOW.SaveTool.Data.CustomerRepository - System.ServiceModel.FaultException`1[System.ServiceModel.ExceptionDetail]: Exception of type 'WOW.Care.Contracts.CustomExceptions.CustomException' was thrown. (Fault Detail is equal to An ExceptionDetail, likely created by IncludeExceptionDetailInFaults=true, whose value is:
WOW.Care.Contracts.CustomExceptions.CustomException: Exception of type 'WOW.Care.Contracts.CustomExceptions.CustomException' was thrown.
   at WOW.Care.Core.Customer.CustomerSearchAllBilingSystems.CustomerDetails(CustomerDetailsByAccountNumberRequest customerDetailsRequest)
   at WOW.Care.Services.Customer.<>c__DisplayClassd.<CustomerDetailsByAccountNumber>b__c()
   at WOW.Care.Core.BaseClasses.ServiceBase.ExecuteFaultHandledOperation[T](Func`1 codetoExecute, IUserDbRequest userDbRequests, IValidator validator, Object request)
   at WOW.Care.Services.Customer.CustomerDetailsByAccountNumber(CustomerDetailsByAccountNumberRequest customerDetailsRequest)
   at Castle.Proxies.Invocations.ICustomer_CustomerDetailsByAccountNumber.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at WOW.Care.Common.Logging.LoggingInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.Abs...).
2016-06-07 15:11:20,897 [6] ERROR WOW.SaveTool.Data.CustomerRepository - System.ServiceModel.FaultException`1[System.ServiceModel.ExceptionDetail]: Exception of type 'WOW.Care.Contracts.CustomExceptions.CustomException' was thrown. (Fault Detail is equal to An ExceptionDetail, likely created by IncludeExceptionDetailInFaults=true, whose value is:
WOW.Care.Contracts.CustomExceptions.CustomException: Exception of type 'WOW.Care.Contracts.CustomExceptions.CustomException' was thrown.
   at WOW.Care.Core.Customer.CustomerSearchAllBilingSystems.CustomerDetails(CustomerDetailsByAccountNumberRequest customerDetailsRequest)
   at WOW.Care.Services.Customer.<>c__DisplayClassd.<CustomerDetailsByAccountNumber>b__c()
   at WOW.Care.Core.BaseClasses.ServiceBase.ExecuteFaultHandledOperation[T](Func`1 codetoExecute, IUserDbRequest userDbRequests, IValidator validator, Object request)
   at WOW.Care.Services.Customer.CustomerDetailsByAccountNumber(CustomerDetailsByAccountNumberRequest customerDetailsRequest)
   at Castle.Proxies.Invocations.ICustomer_CustomerDetailsByAccountNumber.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at WOW.Care.Common.Logging.LoggingInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.Abs...).
2016-06-07 15:28:13,435 [7] ERROR WOW.SaveTool.Data.CustomerRepository - System.ServiceModel.FaultException`1[WOW.SaveTool.Data.Customer.ParameterFaultException]: The range for account number is from 0 to 999999999
 (Fault Detail is equal to WOW.SaveTool.Data.Customer.ParameterFaultException).
2016-06-07 17:17:24,412 [5] ERROR WOW.SaveTool.Data.CustomerRepository - System.ServiceModel.CommunicationException: An error occurred while making the HTTP request to https://apiexternalqa.wideopenwest.com/Enterprise/CareQuery/Customer.svc. This could be due to the fact that the server certificate is not configured properly with HTTP.SYS in the HTTPS case. This could also be caused by a mismatch of the security binding between the client and the server. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.TlsStream.CallProcessAuthentication(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
   at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.PooledStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.ConnectStream.WriteHeaders(Boolean async)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.HttpChannelRequest.WaitForReply(TimeSpan timeout)
   --- End of inner exception stack trace ---

Server stack trace: 
   at System.ServiceModel.Channels.HttpChannelUtilities.ProcessGetResponseWebException(WebException webException, HttpWebRequest request, HttpAbortReason abortReason)
   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.HttpChannelRequest.WaitForReply(TimeSpan timeout)
   at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.SecurityChannelFactory`1.SecurityRequestChannel.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at WOW.SaveTool.Data.Customer.ICustomer.CustomerDetailsByAccountNumber(CustomerDetailsByAccountNumberRequest customerDetailsRequest)
   at WOW.SaveTool.Data.CustomerRepository.GetCustomerInformation(String accountNumber, String username) in c:\@EricStuff\WOW_Development\WOW.SavesTool\Release2\Dev\WOW.SaveTool.Data\CustomerRepository.cs:line 61
2016-06-07 17:17:51,480 [8] ERROR WOW.SaveTool.Data.CustomerRepository - System.TimeoutException: The request channel timed out attempting to send after 00:00:03. Increase the timeout value passed to the call to Request or increase the SendTimeout value on the Binding. The time allotted to this operation may have been a portion of a longer timeout. ---> System.TimeoutException: The HTTP request to 'https://apiexternalqa.wideopenwest.com/Enterprise/WOWProduct/QA/ProductQuery/ProductQuery.svc' has exceeded the allotted timeout of 00:00:03. The time allotted to this operation may have been a portion of a longer timeout. ---> System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at System.ServiceModel.Channels.HttpOutput.WebRequestHttpOutput.GetOutputStream()
   --- End of inner exception stack trace ---
   at System.ServiceModel.Channels.HttpOutput.WebRequestHttpOutput.GetOutputStream()
   at System.ServiceModel.Channels.HttpOutput.Send(TimeSpan timeout)
   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.HttpChannelRequest.SendRequest(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   --- End of inner exception stack trace ---

Server stack trace: 
   at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.SecurityChannelFactory`1.SecurityRequestChannel.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at WOW.SaveTool.Data.ProductQuery.IProductQuery.GetOffers(GetOfferRequest getOfferRequest)
   at WOW.SaveTool.Data.CustomerRepository.GetOffers(Package[] accountPackage, Int32 starRating, Int32 marketId, Int32 tenure, Boolean isCable, Boolean isPhone, Boolean isInternet, EnumsOfferGroup offerGroup, Int32 savesLogId) in c:\@EricStuff\WOW_Development\WOW.SavesTool\Release2\Dev\WOW.SaveTool.Data\CustomerRepository.cs:line 210
