2016-06-09 08:54:45,331 [49] ERROR WOW.SaveTool.Data.CustomerRepository - System.TimeoutException: The request channel timed out while waiting for a reply after 00:00:04.9509951. Increase the timeout value passed to the call to Request or increase the SendTimeout value on the Binding. The time allotted to this operation may have been a portion of a longer timeout. ---> System.TimeoutException: The HTTP request to 'https://apiexternalqa.wideopenwest.com/Enterprise/WOWProduct/QA/ProductQuery/ProductQuery.svc' has exceeded the allotted timeout of 00:00:04.9930000. The time allotted to this operation may have been a portion of a longer timeout. ---> System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetResponse()
   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.HttpChannelRequest.WaitForReply(TimeSpan timeout)
   --- End of inner exception stack trace ---
   at System.ServiceModel.Channels.HttpChannelUtilities.ProcessGetResponseWebException(WebException webException, HttpWebRequest request, HttpAbortReason abortReason)
   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.HttpChannelRequest.WaitForReply(TimeSpan timeout)
   at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   --- End of inner exception stack trace ---

Server stack trace: 
   at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.SecurityChannelFactory`1.SecurityRequestChannel.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at WOW.SaveTool.Data.ProductQuery.IProductQuery.GetOffers(GetOfferRequest getOfferRequest)
   at WOW.SaveTool.Data.CustomerRepository.GetOffers(Package[] accountPackage, Int32 starRating, Int32 marketId, Int32 tenure, Boolean isCable, Boolean isPhone, Boolean isInternet, EnumsOfferGroup offerGroup, Int32 savesLogId) in c:\@EricStuff\WOW_Development\WOW.SavesTool\Release2\Dev\WOW.SaveTool.Data\CustomerRepository.cs:line 210
2016-06-09 09:49:48,901 [7] ERROR WOW.SaveTool.Data.CustomerRepository - System.ServiceModel.FaultException`1[System.ServiceModel.ExceptionDetail]: Exception of type 'WOW.Care.Contracts.CustomExceptions.CustomException' was thrown. (Fault Detail is equal to An ExceptionDetail, likely created by IncludeExceptionDetailInFaults=true, whose value is:
WOW.Care.Contracts.CustomExceptions.CustomException: Exception of type 'WOW.Care.Contracts.CustomExceptions.CustomException' was thrown.
   at WOW.Care.Core.Customer.CustomerSearchAllBilingSystems.CustomerDetails(CustomerDetailsByAccountNumberRequest customerDetailsRequest)
   at WOW.Care.Services.Customer.<>c__DisplayClassd.<CustomerDetailsByAccountNumber>b__c()
   at WOW.Care.Core.BaseClasses.ServiceBase.ExecuteFaultHandledOperation[T](Func`1 codetoExecute, IUserDbRequest userDbRequests, IValidator validator, Object request)
   at WOW.Care.Services.Customer.CustomerDetailsByAccountNumber(CustomerDetailsByAccountNumberRequest customerDetailsRequest)
   at Castle.Proxies.Invocations.ICustomer_CustomerDetailsByAccountNumber.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at WOW.Care.Common.Logging.LoggingInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.Abs...).
2016-06-09 11:19:55,817 [9] ERROR WOW.SaveTool.Data.CustomerRepository - System.ServiceModel.FaultException`1[System.ServiceModel.ExceptionDetail]: Exception of type 'WOW.Care.Contracts.CustomExceptions.CustomException' was thrown. (Fault Detail is equal to An ExceptionDetail, likely created by IncludeExceptionDetailInFaults=true, whose value is:
WOW.Care.Contracts.CustomExceptions.CustomException: Exception of type 'WOW.Care.Contracts.CustomExceptions.CustomException' was thrown.
   at WOW.Care.Core.Customer.CustomerSearchAllBilingSystems.CustomerDetails(CustomerDetailsByAccountNumberRequest customerDetailsRequest)
   at WOW.Care.Services.Customer.<>c__DisplayClassd.<CustomerDetailsByAccountNumber>b__c()
   at WOW.Care.Core.BaseClasses.ServiceBase.ExecuteFaultHandledOperation[T](Func`1 codetoExecute, IUserDbRequest userDbRequests, IValidator validator, Object request)
   at WOW.Care.Services.Customer.CustomerDetailsByAccountNumber(CustomerDetailsByAccountNumberRequest customerDetailsRequest)
   at Castle.Proxies.Invocations.ICustomer_CustomerDetailsByAccountNumber.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at WOW.Care.Common.Logging.LoggingInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.Abs...).
2016-06-09 11:26:03,648 [8] ERROR WOW.SaveTool.Data.CustomerRepository - System.ServiceModel.FaultException`1[System.ServiceModel.ExceptionDetail]: Exception of type 'WOW.Care.Contracts.CustomExceptions.CustomException' was thrown. (Fault Detail is equal to An ExceptionDetail, likely created by IncludeExceptionDetailInFaults=true, whose value is:
WOW.Care.Contracts.CustomExceptions.CustomException: Exception of type 'WOW.Care.Contracts.CustomExceptions.CustomException' was thrown.
   at WOW.Care.Core.Customer.CustomerSearchAllBilingSystems.CustomerDetails(CustomerDetailsByAccountNumberRequest customerDetailsRequest)
   at WOW.Care.Services.Customer.<>c__DisplayClassd.<CustomerDetailsByAccountNumber>b__c()
   at WOW.Care.Core.BaseClasses.ServiceBase.ExecuteFaultHandledOperation[T](Func`1 codetoExecute, IUserDbRequest userDbRequests, IValidator validator, Object request)
   at WOW.Care.Services.Customer.CustomerDetailsByAccountNumber(CustomerDetailsByAccountNumberRequest customerDetailsRequest)
   at Castle.Proxies.Invocations.ICustomer_CustomerDetailsByAccountNumber.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at WOW.Care.Common.Logging.LoggingInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.Abs...).
2016-06-09 12:51:28,233 [6] ERROR WOW.SaveTool.Data.CustomerRepository - System.ServiceModel.FaultException`1[System.ServiceModel.ExceptionDetail]: Exception of type 'WOW.Care.Contracts.CustomExceptions.CustomException' was thrown. (Fault Detail is equal to An ExceptionDetail, likely created by IncludeExceptionDetailInFaults=true, whose value is:
WOW.Care.Contracts.CustomExceptions.CustomException: Exception of type 'WOW.Care.Contracts.CustomExceptions.CustomException' was thrown.
   at WOW.Care.Core.Customer.CustomerSearchAllBilingSystems.CustomerDetails(CustomerDetailsByAccountNumberRequest customerDetailsRequest)
   at WOW.Care.Services.Customer.<>c__DisplayClassd.<CustomerDetailsByAccountNumber>b__c()
   at WOW.Care.Core.BaseClasses.ServiceBase.ExecuteFaultHandledOperation[T](Func`1 codetoExecute, IUserDbRequest userDbRequests, IValidator validator, Object request)
   at WOW.Care.Services.Customer.CustomerDetailsByAccountNumber(CustomerDetailsByAccountNumberRequest customerDetailsRequest)
   at Castle.Proxies.Invocations.ICustomer_CustomerDetailsByAccountNumber.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at WOW.Care.Common.Logging.LoggingInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.Abs...).
2016-06-09 12:51:38,184 [7] ERROR WOW.SaveTool.Data.CustomerRepository - System.ServiceModel.FaultException`1[System.ServiceModel.ExceptionDetail]: Exception of type 'WOW.Care.Contracts.CustomExceptions.CustomException' was thrown. (Fault Detail is equal to An ExceptionDetail, likely created by IncludeExceptionDetailInFaults=true, whose value is:
WOW.Care.Contracts.CustomExceptions.CustomException: Exception of type 'WOW.Care.Contracts.CustomExceptions.CustomException' was thrown.
   at WOW.Care.Core.Customer.CustomerSearchAllBilingSystems.CustomerDetails(CustomerDetailsByAccountNumberRequest customerDetailsRequest)
   at WOW.Care.Services.Customer.<>c__DisplayClassd.<CustomerDetailsByAccountNumber>b__c()
   at WOW.Care.Core.BaseClasses.ServiceBase.ExecuteFaultHandledOperation[T](Func`1 codetoExecute, IUserDbRequest userDbRequests, IValidator validator, Object request)
   at WOW.Care.Services.Customer.CustomerDetailsByAccountNumber(CustomerDetailsByAccountNumberRequest customerDetailsRequest)
   at Castle.Proxies.Invocations.ICustomer_CustomerDetailsByAccountNumber.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at WOW.Care.Common.Logging.LoggingInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.Abs...).
2016-06-09 15:21:46,596 [7] ERROR WOW.SaveTool.Data.CustomerRepository - System.ServiceModel.FaultException`1[System.ServiceModel.ExceptionDetail]: Exception of type 'WOW.Care.Contracts.CustomExceptions.CustomException' was thrown. (Fault Detail is equal to An ExceptionDetail, likely created by IncludeExceptionDetailInFaults=true, whose value is:
WOW.Care.Contracts.CustomExceptions.CustomException: Exception of type 'WOW.Care.Contracts.CustomExceptions.CustomException' was thrown.
   at WOW.Care.Core.Customer.CustomerSearchAllBilingSystems.CustomerDetails(CustomerDetailsByAccountNumberRequest customerDetailsRequest)
   at WOW.Care.Services.Customer.<>c__DisplayClassd.<CustomerDetailsByAccountNumber>b__c()
   at WOW.Care.Core.BaseClasses.ServiceBase.ExecuteFaultHandledOperation[T](Func`1 codetoExecute, IUserDbRequest userDbRequests, IValidator validator, Object request)
   at WOW.Care.Services.Customer.CustomerDetailsByAccountNumber(CustomerDetailsByAccountNumberRequest customerDetailsRequest)
   at Castle.Proxies.Invocations.ICustomer_CustomerDetailsByAccountNumber.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at WOW.Care.Common.Logging.LoggingInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.Abs...).
